---
jobs:
- name: job-upload-release
  public: true
  plan:
  - task: upload-release
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: starkandwayne/concourse}
      run:
        path: echo
        args:
          - "Eventually I will rule the world!"
