jobs:
- name: job-upload-release
  plan:
  - get: source-code
    params:
      depth: 1
    trigger: true
  - config:
      image_resource:
        source:
          repository: starkandwayne/concourse
        type: docker-image
      inputs:
      - name: source-code
      platform: linux
      run:
        path: source-code/nginx_release/ci/tasks/upload-release.sh
    task: upload-release
  public: true
resources:
- name: source-code
  source:
    branch: master
    uri: https://github.com/trunnell1128/sw-concourse-training.git
  type: git

